### ISSUE TITLE
No way to install on modern ubuntu

### ISSUE THREAD

**Issue by guysoft** [phunehehe/philesight#1]
Hey, I have an old ubuntu 15.10, but its too new for ruby 1.8. I can't find how to install and get philesight running. Nor an anything newer than that.

Any way to update the docs/something so I can install it?

Thanks,

**Comment by guysoft** [comment]
Found this comment: https://gist.github.com/phunehehe/5097331#gistcomment-846963

It still fails on ruby 1.9

**Comment by phunehehe** [comment]
Hi @guysoft,
Development of Philesight has ceased (have a look at the web page). You might want to try the replacement from the same author https://github.com/zevv/duc/. This repo is just where I try things out. I found `ncdu` more suitable for my use case.
Cheers,

**Comment by guysoft** [comment]
Already started using duc. Thanks!
